version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 890058568674.dkr.ecr.us-west-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - cd build && make ${COIN} BUILDS=${BUILD}
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/artifacts/${COINNAME}/${ARCH}/*
