version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd build && make ${COIN} BUILDS=${BUILD}
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/artifacts/${COINNAME}/${ARCH}/*
