version: 0.2
batch:
  fast-fail: false
  build-list:
    - identifier: linux_armhf_daemon
      buildspec: codebuild/build.yml
      env:
        variables:
          ARCH: armhf-linux
          BUILD: rpidaemon
      ignore-failure: false
    - identifier: linux_aarch64_daemon
      buildspec: codebuild/build.yml
      env:
        variables:
          ARCH: aarch64-linux
          BUILD: arm64daemon
      ignore-failure: false
    - identifier: linux_x86_64_daemon
      buildspec: codebuild/build.yml
      env:
        variables:
          ARCH: x86_64-linux
          BUILD: linuxdaemon
      ignore-failure: false
    - identifier: linux_x86_64_qt
      buildspec: codebuild/build.yml
      env:
        variables:
          ARCH: x86_64-linux
          BUILD: linuxqt
      ignore-failure: false
    - identifier: windows_x86_64_qt
      buildspec: codebuild/build.yml
      env:
        variables:
          ARCH: x86_64-windows
          BUILD: win64qt
      ignore-failure: false
    - identifier: windows_i686_qt
      buildspec: codebuild/build.yml
      env:
        variables:
          ARCH: i686-windows
          BUILD: win32qt
      ignore-failure: false

artifacts:
  files:
    - '**/*'
  base-directory: '*/Output'
