FROM 890058568674.dkr.ecr.us-west-2.amazonaws.com/coin-nodes:@TARGET@
MAINTAINER gjhurlbu@gmail.com
USER coinnode

# Setup environment
ENV srcDir /home/coinnode/src
ENV PATH /home/coinnode/bin:${PATH}
ENV TERM screen
%=- INSTALLEXPLORER 1
ENV NVM_DIR "/home/coinnode/.nvm"
=%

# Expose the ports
%=+ ISPOOL 0
EXPOSE @P2PPORT@
EXPOSE @RPCPORT@
=%
%=- USEEXPLORER 1
EXPOSE @EXPLORERPORT@
=%
%=- USEP2POOL 1
EXPOSE @P2POOLPORT@
=%
%=- ISPOOL 1
EXPOSE @POOLPORT@
=%
%=? STRATUMPORTS 1
EXPOSE @_@
=%

%=+ POOLNODE 0
# Update the config
ADD startup-node.sh /home/coinnode/startup.sh
=%

%=- POOLNODE 1
# Update the config
ADD @COINNAME@.conf /home/coinnode/.@COINDIR@/@COINNAME@.conf
ADD startup-pool.sh /home/coinnode/startup.sh
=%

USER root
RUN chmod 755 /home/coinnode/startup.sh
USER coinnode

%=- BACKUPFILE 1
# If there is a backup file, add it
ADD backup.tar.gz /home/coinnode/.@COINDIR@
=%

WORKDIR /home/coinnode
ENTRYPOINT /usr/bin/script /dev/null -c "/usr/bin/screen -s /bin/bash /home/coinnode/startup.sh @USEEXPLORER@"
