FROM 890058568674.dkr.ecr.us-west-2.amazonaws.com/coin-nodes:base
MAINTAINER gjhurlbu@gmail.com
USER root

# Setup environment
ENV srcDir /home/coinnode/src
ENV PATH /home/coinnode/bin:${PATH}
ENV USER root

%=- INSTALLEXPLORER 1
# Install mongodb
RUN apt-get install -y \
	-o Dpkg::Options::="--force-overwrite" \
	mongodb

# Install NodeJS & npm
ENV NVM_DIR "/home/coinnode/.nvm"
WORKDIR /tmp
ADD node-v8.7.0-linux-x64.tar.xz /tmp/
RUN rsync -a /tmp/node-v8.7.0-linux-x64/ /usr/local/
RUN rm /usr/local/CHANGELOG.md /usr/local/LICENSE /usr/local/README.md
RUN node -v
=%
	
ARG CACHE_DATE=never
%=- CPUMINER cpuminer-opt
# Install cpuminer-opt
RUN git clone https://github.com/JayDDee/cpuminer-opt ${srcDir}/cpuminer-opt
WORKDIR ${srcDir}/cpuminer-opt
RUN ./autogen.sh
RUN CFLAGS="-O3 -march=corei7-avx -Wall" CXXFLAGS="-O3 -march=corei7-avx -Wall -std=gnu++11" ./configure --with-curl
RUN make -j4
RUN strip -s cpuminer
RUN make install
=%

%=- CPUMINER cpuminer-opt-legacy
RUN git clean -xfd && git reset --hard
RUN git fetch origin legacy && git checkout legacy && git pull
RUN ./autogen.sh
RUN CFLAGS="-O3 -march=corei7-avx -Wall" CXXFLAGS="-O3 -march=corei7-avx -Wall -std=gnu++11" ./configure --with-curl
RUN make -j4
RUN strip -s cpuminer
RUN make install
=%

%=- CPUMINER cpuminer-pooler
# Install minerd (cpuminer)
RUN git clone https://github.com/pooler/cpuminer ${srcDir}/cpuminer
WORKDIR ${srcDir}/cpuminer
RUN ./autogen.sh
RUN ./configure CFLAGS="-O3"
RUN make -j4
RUN make install
=%

%=- CPUMINER cpuminer-blake2s
# Install minerd (cpuminer)
RUN git clone https://github.com/MyCryptoCoins/cpuminer-blake2s.git ${srcDir}/cpuminer
WORKDIR ${srcDir}/cpuminer
RUN ./autogen.sh
RUN ./configure CFLAGS="-O3"
RUN make -j4
RUN make install
=%

# Install config file
ADD @COINNAME@.conf /home/coinnode/.@COINDIR@/@COINNAME@.conf

# Install the daemon
%=- COPYAWSCREDS 1
ADD aws-credentials /home/coinnode/.aws/credentials
USER coinnode
RUN aws s3 cp s3://beirdo-coin-builds/linux_aarch64_daemon/Output/@COINNAME@/aarch64-linux/@DAEMONNAME@ /tmp/
USER root
RUN cp /tmp/@DAEMONNAME@ /usr/local/bin/
=%
%=+ COPYAWSCREDS 0
RUN wget https://beirdo-coin-builds.s3.us-west-2.amazonaws.com/linux_aarch64_daemon/Output/@COINNAME@/aarch64-linux/@DAEMONNAME@ -O /usr/local/bin/@DAEMONNAME@
=%
RUN chmod 755 /usr/local/bin/@DAEMONNAME@

%=- INSTALLEXPLORER 1
# Install iquidus explorer
RUN git clone https://github.com/iquidus/explorer ${srcDir}/explorer
WORKDIR ${srcDir}/explorer
RUN npm install --production --unsafe
ADD explorer.mongo ${srcDir}/explorer/explorer.mongo
ADD explorer-settings.json ${srcDir}/explorer/settings.json
ADD explorer-crontab ${srcDir}/explorer/crontab
ADD explorer-layout.jade ${srcDir}/explorer/view/layout.jade
=%

# Startup script and sudo
ADD startup-node.sh /home/coinnode/startup.sh
RUN chmod 755 /home/coinnode/startup.sh
ADD sudoers-coinnode /etc/sudoers.d/sudoers-coinnode
RUN chmod 400 /etc/sudoers.d/sudoers-coinnode

# Inxtall coin-cli script
ADD coin-cli /usr/local/bin/coin-cli
RUN chmod 755 /usr/local/bin/coin-cli

%=- USEP2POOL 1
# Install p2pool
RUN git clone https://github.com/Beirdo/p2pool ${srcDir}/p2pool -b @COINNAME@
WORKDIR ${srcDir}/p2pool
RUN pip install -r requirements.txt
RUN pip install service_identity
=%

%=- USEOPRETURN 1
# Install the opreturn tools
RUN git clone https://github.com/Beirdo/python-OP_RETURN \
	${srcDir}/python-OP_RETURN
WORKDIR ${srcDir}/python-OP_RETURN
RUN pip install -r requirements.txt
=%

# Fix permissions for coinnode
RUN chown -R coinnode /home/coinnode

# Cleanup
RUN rm -rf /tmp ; mkdir /tmp ; chmod 1777 /tmp
RUN apt-get clean
ENTRYPOINT /bin/bash
