CROSS_TRIPLE := x86_64-w64-mingw32

# Berkeley DB 4.8
BDB_HOST := x86_64-mingw32
BDB_EXTRA := --enable-mingw
BDB_BUILD := build_windows

# OpenSSL
OPENSSL_MACH := mingw64
OPENSSL_EXTRA :=

# Qt5
QT_PLATFORM := -xplatform win32-g++ 
QT_PLATFORM += -no-use-gold-linker
QT_PLATFORM += -platform linux-g++-64 -no-icu
QT_PLATFORM += -device-option CROSS_COMPILE=${CROSS_TRIPLE}-
QT_PLATFORM += -nomake examples -nomake tests
QT_PLATFORM += -I /usr/share/mingw-w64/include
QT_PLATFORM += -I /usr/include/c++/6.3.0

# Boost
BOOST_ARCH := mingw
BOOST_EXTRA := target-os=windows threadapi=win32 abi=ms address-model=64 
BOOST_EXTRA += architecture=x86 binary-format=pe

# miniupnpc
UPNP_MAKEFILE := Makefile.mingw
