FROM beirdo/coinnode:@TARGET@
MAINTAINER gjhurlbu@gmail.com
USER coinnode

# Setup environment
ENV srcDir /home/coinnode/src
ENV TERM screen

# Expose the ports
%=+ ISPOOL 0
EXPOSE @P2PPORT@
EXPOSE @RPCPORT@
=%
%=- USEEXPLORER 1
EXPOSE @EXPLORERPORT@
=%
%=- USEP2POOL 1
EXPOSE @P2POOLPORT@
=%
%=- ISPOOL 1
EXPOSE @COINIUMSERVPORT@
=%

%=+ POOLNODE 0
# Update the config
ADD startup-node.sh /home/coinnode/startup.sh
=%

%=- POOLNODE 1
ADD startup-pool.sh /home/coinnode/startup.sh
=%

RUN chmod 755 /home/coinnode/startup.sh

%=- BACKUPFILE 1
# If there is a backup file, add it
ADD backup.tar.gz /home/coinnode/.@COINNAME@
=%

%=- COPYAWSCREDS 1
ADD aws-credentials /home/coinnode/.aws/credentials
=%

WORKDIR /home/coinnode
ENTRYPOINT /usr/bin/script /dev/null -c "/usr/bin/screen -s /bin/bash /home/coinnode/startup.sh @USEEXPLORER@"
