FROM ubuntu:17.04
MAINTAINER gjhurlbu@gmail.com

# Setup base system
RUN apt-get update && apt-get install -y \
	-o Dpkg::Options::="--force-overwrite" \
	autoconf \
	automake \
	autopoint \
	bash \
	bison \
	build-essential \
	bzip2 \
	cmake \
	flex \
	g++ \
	gettext \
	git \
	g++-multilib libc6-dev-i386 \
	gperf \
	intltool \
	libboost-all-dev \
	libboost-dev \
	libboost-filesystem-dev \
	libboost-program-options-dev \
	libboost-system-dev \
	libboost-thread-dev libssl-dev \
	libcurl4-openssl-dev \
	libdb++-dev \
	libevent-dev \
	libffi-dev \
	libgdk-pixbuf2.0-dev \
	libgmp-dev \
	libjansson-dev \
	libltdl-dev \
	libminiupnpc-dev \
	libncurses5-dev \
	libpng-dev \
	libprotobuf-dev \
	libqrencode-dev \
	libqt5core5a \
	libqt5dbus5 \
	libqt5gui5 \
	libqt5webkit5-dev \
	libssl-dev \
	libtool \
	libtool-bin \
	libxml-parser-perl \
	make \
	mongodb \
	nodejs \
	npm \
	openssl \
	p7zip-full \
	patch \
	perl \
	pkg-config \
	protobuf-compiler \
	python3 \
	qrencode \
	qttools5-dev \
	qttools5-dev-tools \
	rsync \
	ruby \
	scons \
	sed \
	unzip \
	wget \
	xz-utils \
	yasm \
	zip \
	zlib1g-dev

# Setup environment
ENV srcDir /home/coinnode/src
	
# Install cpuminer
RUN git clone https://github.com/JayDDee/cpuminer-opt ${srcDir}/cpuminer-opt
WORKDIR ${srcDir}/cpuminer-opt
RUN ./build.sh
RUN make install

# Install config file
ADD @COINNAME@.conf /home/coinnode/.@COINNAME@/@COINNAME@.conf

# Install the daemon
ADD @DAEMON@ /usr/local/bin/@DAEMON@
RUN chmod 755 /usr/local/bin/@DAEMON@

# Install iquidus explorer
RUN git clone https://github.com/iquidus/explorer ${srcDir}/explorer
WORKDIR ${srcDir}/explorer
RUN npm install --production
ADD explorer.mongo /tmp/explorer.mongo
RUN mongo < /tmp/explorer.mongo
ADD explorer-settings.json ${srcDir}/explorer/settings.json
ADD explorer-crontab ${srcDir}/explorer/crontab

# User creation
WORKDIR /
RUN useradd -m -c "Coin Node" -d /home/coinnode coinnode
RUN mkdir -p /home/coinnode/src
RUN chown -R coinnode /home/coinnode

# Cleanup
RUN rm -rf /tmp ; mkdir /tmp ; chmod 755 /tmp
RUN apt-get clean
