FROM ubuntu:17.04
MAINTAINER gjhurlbu@gmail.com
USER root

# Setup base system
RUN apt-get update && apt-get install -y \
	software-properties-common
RUN add-apt-repository ppa:bitcoin/bitcoin
RUN apt-get update && apt-get install -y \
	-o Dpkg::Options::="--force-overwrite" \
	autoconf \
	automake \
	autopoint \
	awscli \
	bash \
	bison \
	bitcoind \
	build-essential \
	bzip2 \
	cmake \
	curl \
	flex \
	g++ \
        gdb \
	gettext \
	git \
	g++-multilib libc6-dev-i386 \
	gperf \
	intltool \
	libboost-all-dev \
	libboost-dev \
	libboost-filesystem-dev \
	libboost-program-options-dev \
	libboost-system-dev \
	libboost-thread-dev libssl-dev \
	libcurl4-openssl-dev \
	libdb4.8++-dev \
	libevent-dev \
	libffi-dev \
	libgdk-pixbuf2.0-dev \
	libgmp-dev \
	libjansson-dev \
	libkrb5-dev \
	libltdl-dev \
	libminiupnpc-dev \
	libncurses5-dev \
	libpng-dev \
	libprotobuf-dev \
	libqrencode-dev \
	libqt5core5a \
	libqt5dbus5 \
	libqt5gui5 \
	libqt5webkit5-dev \
	libssl-dev \
	libtool \
	libtool-bin \
	libxml-parser-perl \
	make \
	mongodb \
	net-tools \
	openssl \
	p7zip-full \
	patch \
	perl \
	pkg-config \
	protobuf-compiler \
	psutils \
	python3 \
	python-pip \
	qrencode \
	qttools5-dev \
	qttools5-dev-tools \
	rsync \
	ruby \
	scons \
	screen \
	sed \
	sudo \
	unzip \
	vim-tiny \
	wget \
	xz-utils \
	yasm \
	zip \
	zlib1g-dev

# User creation
WORKDIR /
RUN useradd -m -c "Coin Node" -d /home/coinnode coinnode
RUN mkdir -p /home/coinnode/src

# Setup environment
ENV srcDir /home/coinnode/src
ENV PATH /home/coinnode/bin:${PATH}
ENV USER root

%=- USEEXPLORER 1
# Install NodeJS & npm
ENV NVM_DIR "/home/coinnode/.nvm"
WORKDIR /tmp
ADD node-v8.7.0-linux-x64.tar.xz /tmp/
RUN rsync -a /tmp/node-v8.7.0-linux-x64/ /usr/local/
RUN rm /usr/local/CHANGELOG.md /usr/local/LICENSE /usr/local/README.md
RUN node -v
=%
	
# Install cpuminer-opt
ARG CACHE_DATE=never
RUN git clone https://github.com/JayDDee/cpuminer-opt ${srcDir}/cpuminer-opt
WORKDIR ${srcDir}/cpuminer-opt
RUN ./autogen.sh
RUN CFLAGS="-O3 -march=corei7-avx -Wall" CXXFLAGS="-O3 -march=corei7-avx -Wall -std=gnu++11" ./configure --with-curl
RUN make -j4
RUN strip -s cpuminer
RUN make install
#RUN mv /usr/local/bin/cpuminer /usr/local/bin/cpuminer-aesni

#RUN git clean -xfd && git reset --hard
#RUN git fetch origin legacy && git checkout legacy && git pull
#RUN ./autogen.sh
#RUN CFLAGS="-O3 -march=corei7-avx -Wall" CXXFLAGS="-O3 -march=corei7-avx -Wall -std=gnu++11" ./configure --with-curl
#RUN make -j4
#RUN strip -s cpuminer
#RUN make install
#RUN mv /usr/local/bin/cpuminer /usr/local/bin/cpuminer-noaesni

# Install minerd (cpuminer)
RUN git clone https://github.com/pooler/cpuminer ${srcDir}/cpuminer
WORKDIR ${srcDir}/cpuminer
RUN ./autogen.sh
RUN ./configure CFLAGS="-O3"
RUN make -j4
RUN make install

# Install config file
ADD @COINNAME@.conf /home/coinnode/.@COINNAME@/@COINNAME@.conf

# Install the daemon
ADD @DAEMONNAME@ /usr/local/bin/@DAEMONNAME@
RUN chmod 755 /usr/local/bin/@DAEMONNAME@

%=- USEEXPLORER 1
# Install iquidus explorer
RUN git clone https://github.com/iquidus/explorer ${srcDir}/explorer
WORKDIR ${srcDir}/explorer
RUN npm install --production --unsafe
ADD explorer.mongo /tmp/explorer.mongo
ADD explorer-settings.json ${srcDir}/explorer/settings.json
ADD explorer-crontab ${srcDir}/explorer/crontab
=%

# Startup script and sudo
ADD startup.sh /home/coinnode/startup.sh
RUN chmod 755 /home/coinnode/startup.sh
ADD sudoers-coinnode /etc/sudoers.d/sudoers-coinnode
RUN chmod 400 /etc/sudoers.d/sudoers-coinnode

# Inxtall coin-cli script
ADD coin-cli /usr/local/bin/coin-cli
RUN chmod 755 /usr/local/bin/coin-cli

%=- USEP2POOL 1
# Install p2pool
RUN git clone https://github.com/Beirdo/p2pool ${srcDir}/p2pool -b @COINNAME@
WORKDIR ${srcDir}/p2pool
RUN pip install -r requirements.txt
RUN pip install service_identity
=%

%=- USEOPRETURN 1
# Install the opreturn tools
RUN git clone https://github.com/Beirdo/python-OP_RETURN \
	${srcDir}/python-OP_RETURN
WORKDIR ${srcDir}/python-OP_RETURN
RUN pip install -r requirements.txt
=%

# Fix permissions for coinnode
RUN chown -R coinnode /home/coinnode

# Cleanup
RUN rm -rf /tmp ; mkdir /tmp ; chmod 1777 /tmp
RUN apt-get clean
