CROSS_TRIPLE := aarch64-linux-gnu

# Berkeley DB 4.8
BDB_HOST := aarch64-linux
BDB_BUILD := build_unix

# OpenSSL
OPENSSL_MACH := linux-aarch64
OPENSSL_EXTRA :=

# Qt5
QT_PLATFORM := -xplatform linux-aarch64-gnu-g++
QT_PLATFORM += -I /usr/include/c++/6.3.0

# Boost
BOOST_ARCH := aarch64

# miniupnpc
UPNP_MAKEFILE := Makefile
